version: "3.3"
services:
  api:
    build: ./api
    command: uvicorn app:app --reload --workers 1 --host 0.0.0.0 --port 5336
    ports:
      - 5336:5336
    environment:
      - DATABASE_URL=postgresql+pg8000://postgres:postgres@db:5432/foo
    depends_on:
      - db
  db:
    image: postgres:13.4
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=foo